baseURL = "https://pauuu.xyz/"
languageCode = "en-gb"
title = "pauuu.xyz"
theme = "hugo-kiera"
copyright = "©2020 Paul Baker. Don't steal stuff."

[author]
	name = "Paul Baker"
#	github = ""
#	gitlab = ""
#	linkedin = ""
#	facebook = ""
	twitter = "paulie_b"
	instagram = "pauliepower"
#	stackoverflow = ""


